<div class="container-fluid">
    <p/>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-file me-1"></i>
            Fabricante: Novo
        </div>
        <div class="card-body">
            <form method="post">
                <div class="mb-3">
                    <label for="txtcodigo" class="form-label">Código</label>
                    <input name="txtcodigo" type="text" class="form-control" id="txtcodigo" value="<?php echo($model->fabricante->getCodigo())?>" disabled>              
                </div>
                <div class="mb-3">
                    <label for="txtnmfabricante" class="form-label">Nome</label>
                    <input name="txtnmfabricante" type="text" class="form-control" id="txtnmfabricante" value="<?php echo($model->fabricante->getNome())?>">              
                </div>
                <div class="mb-3">
                    <label for="txtdsfabricante" class="form-label">Descrição</label>
                    <input name="txtdsfabricante" type="text" class="form-control" id="txtdsfabricante" value="<?php echo($model->fabricante->getDescricao())?>">              
                </div>
                <div class="mb3">
                    <?php echo($model->message)?>
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
                <a href="Fabricante" class="btn btn-danger">Voltar</a>
            </form>
        </div>
    </div>
</div>
