<div class="container-fluid">
    <p/>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-trash me-1"></i>
            Categoria: Excluir
        </div>
        <div class="card-body">
            <p>Conforma a exclusão dos dados abaixo?</p>
            <hr/>
            <form method="post">
                <input name="txtcodigo" type="hidden" value="<?php echo($model->modelo->getCodigo())?>"/>                  
                <div class="mb-3">
                    <label for="txtcodigo" class="form-label">Código</label>
                    <div class="form-control" id="txtcodigo"><?php echo($model->modelo->getCodigo())?></div>              
                </div>
                <div class="mb-3">
                    <label for="txttipo" class="form-label">Tipo</label>
                    <div class="form-control" id="txttipo"><?php echo($model->modelo->getTipo()->getNome())?></div>              
                </div>
                <div class="mb-3">
                    <label for="txtfabricante" class="form-label">Fabricante</label>
                    <div class="form-control" id="txtfabricante"><?php echo($model->modelo->getFabricante()->getNome())?></div>              
                </div>
                <div class="mb-3">
                    <label for="txtnome" class="form-label">Nome</label>
                    <div class="form-control" id="txtdsorigem"><?php echo($model->modelo->getNome())?></div>              
                </div>
                <div class="mb-3">
                    <label for="txtnumero" class="form-label">Número</label>
                    <div class="form-control" id="txtnumero"><?php echo($model->modelo->getNumero())?></div>              
                </div>
                <div class="mb-3">
                    <label for="txtdsdescricao" class="form-label">Descrição</label>
                    <div class="form-control" id="txtdsdescricao"><?php echo($model->modelo->getDescricao())?></div>              
                </div>
                <div class="mb3">
                    <?php echo($model->message)?>
                </div>
                <button type="submit" class="btn btn-primary">Sim</button>
                <a href="Modelo" class="btn btn-danger">Não</a>
            </form>
        </div>
    </div>
</div>
