<div class="container-fluid">
    <p/>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>Perfil: Tabela
        </div>
        <div class="card-body">
            <a class="btn btn-primary" href="Role/insert">Novo...</a>
            <hr/>
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th></th>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>Descrição</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>Descrição</th>
                    </tr>
                </tfoot>
                <tbody>
                <?php
                if($model != null)
                {
                    foreach($model as $item)
                    {?>
                        <tr>
                            <td>
                                <a href="Role/edit/<?php echo($item->getId())?>" class="btn btn-primary btn-sm" ><i class="fa fa-edit"></i></a>
                                <a href="Access/index/<?php echo($item->getId())?>" class="btn btn-secondary btn-sm"><i class="fa fa-flag"></i></a>
                                <a href="Role/delete/<?php echo($item->getId())?>" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                            </td>
                            <td><?php echo($item->getId())?></td>
                            <td><?php echo($item->getName())?></td>
                            <td><?php echo($item->getDescription())?></td>
                        </tr>
                    <?php 
                    }
                }?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    window.addEventListener('DOMContentLoaded', event => {
        // Simple-DataTables
        // https://github.com/fiduswriter/Simple-DataTables/wiki

        const datatablesSimple = document.getElementById('datatablesSimple');
        if (datatablesSimple) {
            new simpleDatatables.DataTable(datatablesSimple);
        }
    });
</script>